CadeMeuMedico/Controllers/MedicoController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CadeMeuMedico.Models;

namespace CadeMeuMedico.Controllers
{
    public class MedicoController : Controller
    {
        private ModeloDeDados db = new ModeloDeDados();

        // GET: Medico
        public ActionResult Index()
        {
            var medicos = db.Medicos.Include(m => m.Cidades).Include(m => m.Especialidades);
            return View(medicos.ToList());
        }

        // GET: Medico/Detalhes
        public ActionResult Details(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Medicos medicos = db.Medicos.Find(id);
            if (medicos == null)
            {
                return HttpNotFound();
            }
            return View(medicos);
        }

        // GET: Medico/Adicionar
        public ActionResult Create()
        {
            ViewBag.IDCidade = new SelectList(db.Cidades, "IDCidade", "Nome");
            ViewBag.IDEspecialidade = new SelectList(db.Especialidades, "IDEspecialidade", "Nome");
            return View();
        }

        // POST: Medico/Adicionar        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "IDMedico,CRM,Nome,Endereco,Bairro,Email,AtendePorConvenio,TemClinica,WebsiteBlog,IDCidade,IDEspecialidade")] Medicos medicos)
        {
            if (ModelState.IsValid)
            {
                db.Medicos.Add(medicos);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.IDCidade = new SelectList(db.Cidades, "IDCidade", "Nome", medicos.IDCidade);
            ViewBag.IDEspecialidade = new SelectList(db.Especialidades, "IDEspecialidade", "Nome", medicos.IDEspecialidade);
            return View(medicos);
        }
        // GET: Medico/Atualizar
        public ActionResult Edit(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Medicos medicos = db.Medicos.Find(id);
            if (medicos == null)
            {
                return HttpNotFound();
            }
            ViewBag.IDCidade = new SelectList(db.Cidades, "IDCidade", "Nome", medicos.IDCidade);
            ViewBag.IDEspecialidade = new SelectList(db.Especialidades, "IDEspecialidade", "Nome", medicos.IDEspecialidade);
            return View(medicos);
        }

        // POST: Medico/Atualizar       
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "IDMedico,CRM,Nome,Endereco,Bairro,Email,AtendePorConvenio,TemClinica,WebsiteBlog,IDCidade,IDEspecialidade")] Medicos medicos)
        {
            if (ModelState.IsValid)
            {
                db.Entry(medicos).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.IDCidade = new SelectList(db.Cidades, "IDCidade", "Nome", medicos.IDCidade);
            ViewBag.IDEspecialidade = new SelectList(db.Especialidades, "IDEspecialidade", "Nome", medicos.IDEspecialidade);
            return View(medicos);
        }

        // GET: Medico/Deletar
        public ActionResult Delete(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Medicos medicos = db.Medicos.Find(id);
            if (medicos == null)
            {
                return HttpNotFound();
            }
            return View(medicos);
        }

        // POST: Medico/Deletar
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(long id)
        {
            Medicos medicos = db.Medicos.Find(id);
            db.Medicos.Remove(medicos);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

CadeMeuMedico/Views/Layout.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>My Doctors @ViewBag.Title</title>
    @*materialize*@
    <link href="http://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="~/Content/materializecss/materialize.min.css" media="screen,projection"/>
    <link rel="stylesheet" href="~/Content/CSS/Medico/Layout.css" />
    
    @*bootstrap*@
    @*<link href="~/Content/bootstrap.min.css" rel="stylesheet" media="screen"/>*@          
</head>
<body>    
    <nav id="menu">
        <div class="nav-wrapper">
            <a href="#!" class="brand-logo center">Doctors
            <i class="medium material-icons">work</i>
            </a>            
            <a href="#" data-activates="mobile-demo" class="button-collapse"><i class="material-icons">menu</i></a>            
            <ul class="right hide-on-med-and-down">                                
                <li>
                    @Html.ActionLink("Inicio", "Index", "Home")
                </li>
                <li id="menuMedicos">
                    @Html.ActionLink("Médicos", "Index", "Medico") 
                </li>               
            </ul>
            <ul class="side-nav" id="mobile-demo">
                <li>
                    <div class="userView">
                        <div class="background">
                            <img id="fundo" src="~/Content/CSS/_imagens/fundo-medico.jpg"/>
                        </div>
                        <a href="#!user"><img class="circle" src="~/Content/CSS/_imagens/perfil-medico.png"></a>
                        <a href="#!name"><span class="black-text name">My Doctors</span></a>
                        <a href="#!email"><span class="black-text email">CRM para feito saber ao está seu Médico para sua consulta</span></a>
                    </div>
                </li>
                <li>
                    @Html.ActionLink("Inicio", "Index", "Home")
                </li>
                <li>
                    @Html.ActionLink("Médicos", "Index", "Medico")
                </li>
            </ul>
        </div>
    </nav>
                  
    <div class="container body-content">
        @RenderBody()                
    </div>
    @*Jquery*@
    <script src="~/Scripts/jquery-3.1.1.min.js"></script>
    @*bootstrap js*@
    @*<script src="~/Scripts/bootstrap.min.js"></script>*@
    @*materialize js*@
    <script src="https://code.jquery.com/jquery-2.1.1.min.js"></script>    
    <script src="~/Scripts/materialize.min.js"></script>
     
    <script>
        $(document).ready(function () { })
        $(".button-collapse").sideNav();
    </script>
    
    <script>
        $(document).ready(function () {
            $('select').material_select();
        });
    </script>
    @RenderSection("script", required: false)
    
    <footer id="rodape" class="page-footer">
        <div class="container">
            <div class="row">
                <div class="col 16 s12">
                    <h5 class="white-text">My Doctors</h5>
                    <p class="grey-text text-lighten-4">CRM para feito saber ao está seu Médico para sua consulta</p>
                </div>                
            </div>
        </div>
        <div class="footer-copyright">
            <div class="container">
                © 2017 Desenvolvido por Alexander Oliveira
                <a class="grey-text text-lighten-4 right" href="https://www.linkedin.com/in/alexander-pereira-oliveira-5b2013104/" target="_blank">
                    <img src="~/Content/CSS/_imagens/linkedin.png"/>
                </a>
            </div>
        </div>
    </footer>
                   
</body>
</html>